2025-06-13 18:45:39,317 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert_info\urls.py changed, reloading.
2025-06-13 18:45:58,293 - ERROR - Internal Server Error: /download/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: get_file() missing 1 required positional argument: 'request'
2025-06-13 18:48:13,413 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 18:48:56,837 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 18:49:01,904 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 18:54:25,218 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:03:27,005 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:09:34,866 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:09:38,581 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:11:44,623 - WARNING - Method Not Allowed: /info/
2025-06-13 19:11:53,985 - ERROR - Internal Server Error: /info/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\lenovo\concert_molded\concert_info\concert\views.py", line 30, in post
    if serializer.is_valid():
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\serializers.py", line 216, in is_valid
    assert hasattr(self, 'initial_data'), (
AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
2025-06-13 19:12:31,549 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:12:38,715 - ERROR - Internal Server Error: /info/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: concert_information.information

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\lenovo\concert_molded\concert_info\concert\views.py", line 31, in post
    info = serializer.save()
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: concert_information.information
2025-06-13 19:17:26,710 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:17:37,692 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:20:13,224 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:21:27,978 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:21:42,409 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:24:24,421 - WARNING - Bad Request: /info/
2025-06-13 19:25:07,959 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert_info\urls.py changed, reloading.
2025-06-13 19:25:17,023 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert_info\urls.py changed, reloading.
2025-06-13 19:25:41,023 - WARNING - Not Found: /download/
2025-06-13 19:25:55,026 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert_info\urls.py changed, reloading.
2025-06-13 19:25:58,865 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert_info\urls.py changed, reloading.
2025-06-13 19:26:03,823 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert_info\urls.py changed, reloading.
2025-06-13 19:26:34,055 - ERROR - Internal Server Error: /download/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\concert_molded\concert_info\concert\views.py", line 55, in get_file
    information["pays"].append(obj.pays)
AttributeError: 'Information' object has no attribute 'pays'
2025-06-13 19:27:18,668 - ERROR - Internal Server Error: /download/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\concert_molded\concert_info\concert\views.py", line 54, in get_file
    information["pays"].append(obj.pays)
KeyError: 'pays'
2025-06-13 19:27:36,945 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:27:40,853 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:28:22,201 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:28:47,432 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:28:52,582 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:28:56,444 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:29:00,346 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:29:10,303 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
2025-06-13 19:30:05,769 - INFO - C:\Users\lenovo\concert_molded\concert_info\concert\views.py changed, reloading.
